### ISSUE TITLE
modbus_util.js close leads to "Callback is not a function error" in modbus-serial

### ISSUE THREAD

**Issue by mike-goetz** [orlopau/sma_modbus#1]
modbus-serial relies on a callback function. 

Not providing a callback function in modbus_util.js close leads to the "Callback is not a function error".

**Comment by orlopau** [comment]
Done via #2

**Comment by hvanoch** [comment]
Could you also publish this changes to the npm repository (https://www.npmjs.com/package/sma_modbus) This changes is not in there yet.

**Comment by orlopau** [comment]
@hvanoch Thanks for the reminder, should be published now in v2.2.3.
